version: '3.3'

networks:
  app:
    driver: bridge

services:
  # Single-node Kafka setup for development.
  kafka-zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - app
    ports:
      - 2181:2181
    volumes:
      - ./app-volume/kafka-zookeeper:/bitnami/zookeeper
  kafka-broker:
    image: bitnami/kafka:latest
    depends_on:
      - kafka-zookeeper
    networks:
      - app
    ports:
      - 9092:9092
    volumes:
      - ./app-volume/kafka-broker:/bitnami/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ALLOW_PLAINTEXT_LISTENER: "yes"

  # Single-node Cassandra setup for development.
  cassandra:
    image: bitnami/cassandra:latest
    networks:
      - app
    ports:
      - 7000:7000
    volumes:
      - ./app-volume/cassandra:/bitnami/cassandra

    environment:
      CASSANDRA_TRANSPORT_PORT_NUMBER: 7000
      CASSANDRA_USER: cassandra-dev
      CASSANDRA_PASSWORD: cassandra-dev-pass
      CASSANDRA_HOST: localhost
    